BakeryMarkTest/Controllers/MenuItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using BakeryMarkTest.Data;
using BakeryMarkTest.Models;
using Microsoft.AspNetCore.Authorization;

namespace BakeryMarkTest.Controllers
{
    public class MenuItemsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public MenuItemsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: MenuItems
        public async Task<IActionResult> Index()
        {
            ViewBag.products = await _context.MenuItem.ToListAsync();
            return View(ViewBag.products);
        }

        // GET: SearchForMenuItem
        public async Task<IActionResult> SearchForMenuItem()
        {
            return View();
        }

        // POST: ShowSearchResult
        public async Task<IActionResult> ShowSearchResult(string SearchItem)
        {
            ViewBag.products = await _context.MenuItem.Where(j => j.Name.Contains(SearchItem)).ToListAsync();
            return View("Index", ViewBag.products);
        }

        // GET: MenuItems/Details/5
        //HTTP GET route to details page, address is localhost:XXXXX/ItemDetails/{id}
        //[HttpGet("ItemDetails/{id}")] Removed so as to allow use of query string at localhost:XXXXX/MenuItems/Details?id=2 and route localhost:XXXXX/MenuItems/Details/2
        public async Task<IActionResult> Details(string? id, string name)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menuItem = await _context.MenuItem
                .FirstOrDefaultAsync(m => m.MenuItemId == id);
            if (menuItem == null)
            {
                return NotFound();
            }

            return View(menuItem);
        }

        // GET: MenuItems/Create
        [Authorize(Roles = "Admin")]
        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        // POST: MenuItems/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("MenuItemId,Name,Description,Price,NumberOfCalories,IsVegan,IsVegeterian,ImagePath")] MenuItem menuItem)
        {
            if (ModelState.IsValid)
            {
                _context.Add(menuItem);
                await _context.SaveChangesAsync();
                //return RedirectToAction(nameof(Index));
                return RedirectToAction("Details", new {id = menuItem.MenuItemId});
            }
            return View(menuItem);
        }

        // GET: MenuItems/Edit/5
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menuItem = await _context.MenuItem.FindAsync(id);
            if (menuItem == null)
            {
                return NotFound();
            }
            return View(menuItem);
        }

        // POST: MenuItems/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("MenuItemId,Name,Description,Price,NumberOfCalories,IsVegan,IsVegeterian,ImagePath")] MenuItem menuItem)
        {
            if (id != menuItem.MenuItemId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(menuItem);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MenuItemExists(menuItem.MenuItemId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(menuItem);
        }

        // GET: MenuItems/Delete/5
        //added route for deletion method that binds id parameter  
        [HttpGet("DeleteMenuItem/{id}")]
        [Authorize(Roles = "Admin")]
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var menuItem = await _context.MenuItem
                .FirstOrDefaultAsync(m => m.MenuItemId == id);
            if (menuItem == null)
            {
                return NotFound();
            }

            return View(menuItem);
        }

        // POST: MenuItems/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            var menuItem = await _context.MenuItem.FindAsync(id);
            _context.MenuItem.Remove(menuItem);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MenuItemExists(string id)
        {
            return _context.MenuItem.Any(e => e.MenuItemId == id);
        }

        [HttpGet("ApiGetAll")]
        public IEnumerable<MenuItem> Get()
        {

            List<MenuItem> menuItems = _context.MenuItem.ToList();

            IEnumerable<MenuItem> result = menuItems.AsEnumerable();
            return result;
        }
    }
}

BakeryMarkTest/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - The Lovin' Oven</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header class="header">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"> <img src=~/Images/LogoWhite.png width="100" height="100"> </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">


                        <li class="nav-item">
                            <a class="nav-link text-light bg-none" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-light bg-none" asp-area="" asp-controller="MenuItems" asp-action="Index">Menu</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-light bg-none" asp-area="" asp-controller="Home" asp-action="OurMission">Our Mission</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-light bg-none" asp-area="" asp-controller="Home" asp-action="ContactUs">Contact Us</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link text-light bg-none" asp-area="" asp-controller="Home" asp-action="Locations">Locations</a>
                        </li>



                    </ul>
                </div>
                
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>



   @* This is our footer stuff*@
    <footer class="border-top footer text-muted">
        <div class="container text-light">
            &copy; 2022 - The Lovin' Oven - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>






    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>